steps:
  - name: gcr.io/cloud-builders/docker
    dir: backend
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/madejadictas-api:latest",
        ".",
      ]
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "push",
        "gcr.io/$PROJECT_ID/madejadictas-api:latest",
      ]
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "madejadictas-api",
        "--image",
        "gcr.io/$PROJECT_ID/madejadictas-api:latest",
        "--region",
        "us-central1",
        "--allow-unauthenticated",
        "--set-env-vars",
        "ADMIN_API_KEY=${_ADMIN_API_KEY}",
      ]
images:
  - gcr.io/$PROJECT_ID/madejadictas-api:latest
substitutions:
  _ADMIN_API_KEY: lanas-colores-2024
